### ISSUE TITLE
Extract results from runs

### ISSUE THREAD

**Issue by AnyaHe** [yubryanj/Complex-Social-Systems-PySC2#2]
In order to evaluate the quality of the reward schemes, we need to be able to extract the results.

One option would be to save the reward and dump it into a pickle-file (see https://github.com/yubryanj/Complex-Social-Systems-PySC2/blob/889a2acbc46723f54c937e6cb37daf2709e0a185/pysc2-tutorial/4.%20Building%20a%20Sparse%20Reward%20Agent/sparse_agent.py#L158).

**Comment by yubryanj** [comment]
The rewards are now extracted within the step function -- and we can store the rewards in the run.py script!

Closing :)
